language: go
go:
  - 1.4
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script:
  - go get -u github.com/golang/lint/golint
  - golint ./...
  - test `gofmt -l . | wc -l` = 0
  - make test

install:
  - go get -t -d -v ./..
